set(CMAKE_ASM_OUTPUT_EXTENSION ".rel")
# set(CMAKE_ASM_COMPILE_OBJECT  "<CMAKE_ASM_COMPILER> <DEFINES> <INCLUDES> <FLAGS> <OBJECT> <SOURCE>")
set(CMAKE_ASM_COMPILE_OBJECT  "<CMAKE_ASM_COMPILER> <DEFINES> <INCLUDES> -plosgff <OBJECT> <SOURCE>")
set(CMAKE_ASM_SOURCE_FILE_EXTENSIONS ".s")
